apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - base
  - externalsecrets

# Common labels applied to all resources

# Image transformation (can be overridden via kustomize)
images:
  - name: homelabplatformacr.azurecr.io/platform-api
    newTag: v0.1.6
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: homelab-platform
